In [18]:
from pathlib import Path
import pandas as pd
import json

In [19]:
data_path = (
    Path.cwd().parent.parent.parent  # Repository root
    / "data"
    / "weather"
    / "open_meteo.json"
)

In [20]:
with open(data_path, 'r') as file:
    data = json.load(file)

In [21]:
df = pd.DataFrame(data['daily'])

In [27]:
df.head()

,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,sunset,shortwave_radiation_sum,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration
0,2010-01-01,0,28.6,13.8,21.4,27.9,13.0,20.4,2010-01-01T00:11,2010-01-01T11:07,17.54,0.0,0.0,0.0,0.0,9.4,23.4,341,4.02
1,2010-01-02,0,27.2,13.2,19.9,25.5,11.9,18.3,2010-01-02T00:12,2010-01-02T11:08,17.84,0.0,0.0,0.0,0.0,12.6,30.2,336,4.22
2,2010-01-03,0,27.8,12.6,20.0,27.0,11.6,18.8,2010-01-03T00:12,2010-01-03T11:08,17.97,0.0,0.0,0.0,0.0,10.2,25.6,325,4.00
3,2010-01-04,1,27.9,12.7,20.3,27.4,11.2,19.0,2010-01-04T00:12,2010-01-04T11:09,18.20,0.0,0.0,0.0,0.0,8.1,20.2,166,3.76
4,2010-01-05,1,29.5,13.8,21.5,29.4,13.0,20.3,2010-01-05T00:13,2010-01-05T11:09,17.87,0.0,0.0,0.0,0.0,9.8,16.9,336,3.83

In [29]:
df.tail()

,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,sunset,shortwave_radiation_sum,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration
4911,2023-06-13,55,29.6,23.6,26.3,32.1,26.5,28.8,2023-06-12T22:52,2023-06-13T12:19,13.42,3.7,3.7,0.0,12.0,20.2,40.7,170,3.57
4912,2023-06-14,61,26.0,23.7,24.7,28.7,26.3,27.1,2023-06-13T22:53,2023-06-14T12:19,3.81,9.7,9.7,0.0,13.0,21.3,37.4,163,1.43
4913,2023-06-15,51,31.4,24.6,27.2,34.6,26.9,29.5,2023-06-14T22:53,2023-06-15T12:19,16.30,0.5,0.5,0.0,3.0,26.0,49.3,171,4.37
4914,2023-06-16,63,32.3,25.4,28.2,35.8,27.7,30.8,2023-06-15T22:53,2023-06-16T12:19,18.25,3.2,3.2,0.0,3.0,23.5,46.1,171,4.99
4915,2023-06-17,51,33.0,25.6,28.8,36.7,28.8,32.1,2023-06-16T22:53,2023-06-17T12:20,22.47,0.6,0.6,0.0,4.0,25.2,47.5,174,5.63

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   time                        4916 non-null   object
 1   weathercode                 4916 non-null   int64
 2   temperature_2m_max          4916 non-null   float64
 3   temperature_2m_min          4916 non-null   float64
 4   temperature_2m_mean         4916 non-null   float64
 5   apparent_temperature_max    4916 non-null   float64
 6   apparent_temperature_min    4916 non-null   float64
 7   apparent_temperature_mean   4916 non-null   float64
 8   sunrise                     4916 non-null   object
 9   sunset                      4916 non-null   object
 10  shortwave_radiation_sum     4916 non-null   float64
 11  precipitation_sum           4916 non-null   float64
 12  rain_sum                    4916 non-null   float64
 13  snowfall_sum                4916 non-null   float64
 14  precipitation_hours         4916 non-null   float64
 15  windspeed_10m_max           4916 non-null   float64
 16  windgusts_10m_max           4916 non-null   float64
 17  winddirection_10m_dominant  4916 non-null   int64
 18  et0_fao_evapotranspiration  4916 non-null   float64
dtypes: float64(14), int64(2), object(3)
memory usage: 729.8+ KB